FPS = 60
SCREEN_WIDTH = 1030
SCREEN_HEIGHT = 600
UP_WALL_Y = 0
TOP_LEFT_SURFACE = (0,0) 
BACKGROUND_COLOR = (0, 0, 0)                         
BRICK_IMAGE = ['./images/brick.png','./images/brick1.png','./images/brick2.png','./images/brick3.png']
SIDE_BORDER_WIDTH = 20
BORDER_LOCATION = [TOP_LEFT_SURFACE,(SCREEN_WIDTH-SIDE_BORDER_WIDTH, UP_WALL_Y),TOP_LEFT_SURFACE]  
UP_BORDER_NUMBER = 2
UP_BORDER_HEIGHT = 35

BALL_X_SPEED = (2, 3)
BALL_Y_SPEED = (2, 3) 
DEFAULT_NUMBER_OF_BALLS = 2
DEFAULT_NUMBER_OF_LIVES = 3
COLISION_TOLERANCE = 4
STICK_TEXTURE = "./images/greenbar.png"

COLOR_BLACK = (0,0,0)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (255, 0, 0, 0)
 
BRICK_OFFSET_X = 50
BRICK_OFFSET_Y = 30
POINTS_PER_BRICK = 10
RIGHT_WALL_X = 1000

STICK_LENGTH = 107
STICK_HEIGHT = 22
STICK_Y_POSITION = 550
 
BALL_RADIUS = 5
 
FONT = 'freesansbold.ttf'
FONT_SIZE =35